export type RootStackParamList = {
  Onboarding: undefined;
  Tutorial: undefined;
  ProfileSelect: undefined;
  Recognition: { profileId: string; simulateLowConfidence?: boolean };
  Training: { gestureLabel?: string; isPractice?: boolean };
  Teach: undefined;
  Teaching: { gestureId?: string } | undefined;
  Parent: undefined;
  ProfileManager: undefined;
  ParentalGate: { target: string };
  Admin: undefined;
  Dashboard: undefined;
  Progress: undefined;
  ProgressChart: { gestureId: string };
  CaregiverReport: undefined;
  CommunicationInsights: undefined;
  Help: undefined;
  PracticeScheduler: undefined;
};
