export type RootStackParamList = {
  Onboarding: undefined;
  Tutorial: undefined;
  ProfileSelect: undefined;
  Recognition: { profileId: string; simulateLowConfidence?: boolean };
  Correction: undefined;
  Training: { gestureLabel?: string; isPractice?: boolean };
  Practice: undefined;
  Teach: undefined;
  Teaching: undefined;
  Parent: undefined;
  ProfileManager: undefined;
  ParentalGate: { target: string };
  Admin: undefined;
  Dashboard: undefined;
  Progress: undefined;
  ProgressChart: { gestureId: string };
  Help: undefined;
  PracticeScheduler: undefined;
};
