export type RootStackParamList = {
  Onboarding: undefined;
  Tutorial: undefined;
  ProfileSelect: undefined;
  Recognition: { profileId: string; simulateLowConfidence?: boolean };
  Training: { gestureLabel?: string; isPractice?: boolean };
  Practice: undefined;
  GesturePractice: undefined;
  Teach: undefined;
  Teaching: { gestureId?: string } | undefined;
  Parent: undefined;
  ProfileManager: undefined;
  ParentalGate: { target: string };
  Admin: undefined;
  Dashboard: undefined;
  Progress: undefined;
  ProgressChart: { gestureId: string };
   CaregiverReport: undefined;
   Schedule: undefined;
   DailySuccess: undefined;
   CommunicationInsights: undefined;
   PrivacySettings: undefined;
   Help: undefined;
   PracticeScheduler: undefined;
};
