#!/usr/bin/env python3
"""Recover all historical completed TODO entries from git history.

This script auto-discovers every historical path that ends with `todo.md`
and extracts completed entries from all of them.

It writes an auto-generated section into docs/planning/todo-done.md between:
<!-- AUTO-GENERATED-DONE-HISTORY:START -->
<!-- AUTO-GENERATED-DONE-HISTORY:END -->
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

DONE_PATH = Path("docs/planning/todo-done.md")
START_MARKER = "<!-- AUTO-GENERATED-DONE-HISTORY:START -->"
END_MARKER = "<!-- AUTO-GENERATED-DONE-HISTORY:END -->"

DONE_PATTERN = re.compile(r"^- \[[xX]\]\s+(.+)$", re.MULTILINE)
PATH_PATTERN = re.compile(r"(^|/)TODO\.md$")


@dataclass
class DoneEntry:
    title: str
    description: str
    source_path: str
    first_seen_date: str
    first_seen_commit: str
    first_seen_subject: str


def run_git(args: List[str]) -> str:
    return subprocess.check_output(["git", *args], text=True).strip()


def discover_todo_paths() -> List[str]:
    # Search every reachable commit tree for files named todo.md (any directory).
    paths = set()

    commits = run_git(["rev-list", "--all"]).splitlines()
    for commit in commits:
        try:
            names = run_git(["ls-tree", "-r", "--name-only", commit])
        except subprocess.CalledProcessError:
            continue

        for line in names.splitlines():
            candidate = line.strip()
            if PATH_PATTERN.search(candidate):
                paths.add(candidate)

    # Safety net for known legacy/current locations even if history is shallow.
    paths.update({"docs/todo.md", "docs/planning/todo.md"})

    discovered = []
    for path in sorted(paths):
        # Keep only paths that exist at least once in history.
        try:
            run_git(["log", "--oneline", "--", path])
            discovered.append(path)
        except subprocess.CalledProcessError:
            continue

    return discovered


def collect_history(todo_paths: List[str]) -> Tuple[List[DoneEntry], Dict[str, int]]:
    entries: Dict[Tuple[str, str, str], DoneEntry] = {}
    path_counts: Dict[str, int] = {path: 0 for path in todo_paths}

    for todo_path in todo_paths:
        log_output = run_git(
            [
                "log",
                "--reverse",
                "--date=short",
                "--format=%H|%ad|%s",
                "--",
                todo_path,
            ]
        )

        for line in log_output.splitlines():
            commit_hash, commit_date, commit_subject = line.split("|", 2)
            try:
                content = run_git(["show", f"{commit_hash}:{todo_path}"])
            except subprocess.CalledProcessError:
                continue

            for match in DONE_PATTERN.finditer(content):
                raw_text = " ".join(match.group(1).split())

                # Preferred format: "**Title**: Description"
                if raw_text.startswith("**") and "**: " in raw_text:
                    title_part, desc_part = raw_text.split("**: ", 1)
                    title = title_part.replace("**", "").strip()
                    description = desc_part.strip()
                else:
                    title = "Task"
                    description = raw_text

                key = (todo_path, title, description)
                if key in entries:
                    continue
                entries[key] = DoneEntry(
                    title=title,
                    description=description,
                    source_path=todo_path,
                    first_seen_date=commit_date,
                    first_seen_commit=commit_hash[:7],
                    first_seen_subject=commit_subject,
                )
                path_counts[todo_path] += 1

    sorted_entries = sorted(
        entries.values(),
        key=lambda item: (item.first_seen_date, item.source_path.lower(), item.title.lower()),
    )
    return sorted_entries, path_counts


def build_markdown(entries: List[DoneEntry], todo_paths: List[str], path_counts: Dict[str, int]) -> str:
    lines: List[str] = []
    lines.append("## 6) Historical recovery from git timeline (auto-generated)")
    lines.append("")
    lines.append(
        "This section is generated by `scripts/planning/recover_todo_done_history.py` by walking "
        "git history commit-by-commit and extracting every unique `[x]` task from all historical `todo.md` paths."
    )
    lines.append("")
    lines.append("Discovered TODO paths:")
    for path in todo_paths:
        lines.append(f"- `{path}`")
    lines.append("")
    lines.append("Recovered entries by TODO path:")
    for path in todo_paths:
        lines.append(f"- `{path}`: **{path_counts.get(path, 0)}** recovered done entries")
    lines.append("")

    current_date = ""
    for item in entries:
        if item.first_seen_date != current_date:
            current_date = item.first_seen_date
            lines.append(f"### {current_date}")
            lines.append("")

        lines.append(f"- [x] **{item.title}:** {item.description}")
        lines.append(
            "  - First seen done in "
            f"`{item.source_path}` at commit `{item.first_seen_commit}` ({item.first_seen_subject})."
        )

    lines.append("")
    lines.append(f"- Total recovered done entries: **{len(entries)}**.")
    lines.append("")
    return "\n".join(lines)


def update_done_file(section_markdown: str) -> None:
    DONE_PATH.parent.mkdir(parents=True, exist_ok=True)
    text = DONE_PATH.read_text() if DONE_PATH.exists() else ""

    if START_MARKER not in text or END_MARKER not in text:
        text = text.rstrip() + "\n\n" + START_MARKER + "\n" + END_MARKER + "\n"

    start_index = text.index(START_MARKER) + len(START_MARKER)
    end_index = text.index(END_MARKER)

    updated = text[:start_index] + "\n\n" + section_markdown + "\n" + text[end_index:]
    DONE_PATH.write_text(updated)


def main() -> None:
    todo_paths = discover_todo_paths()
    entries, path_counts = collect_history(todo_paths)
    section = build_markdown(entries, todo_paths, path_counts)
    update_done_file(section)
    print(
        f"Recovered {len(entries)} historical done entries from {len(todo_paths)} TODO path(s) into {DONE_PATH}"
    )


if __name__ == "__main__":
    main()
