const globals = require('globals');
const tseslint = require('typescript-eslint');
const react = require('eslint-plugin-react');
const reactHooks = require('eslint-plugin-react-hooks');
const jest = require('eslint-plugin-jest');

module.exports = [
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parser: tseslint.parser,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.jest,
        '__DEV__': 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      'react': react,
      'react-hooks': reactHooks,
      'jest': jest,
    },
    rules: {
      'react/react-in-jsx-scope': 'off',
      'react/jsx-uses-react': 'off',
      'react-hooks/exhaustive-deps': 'warn',
      '@typescript-eslint/no-unused-vars': 'warn',
    },
  },
  {
    // Explicitly ignore generated files and directories
    ignores: [
      'android/',
      'ios/',
      'node_modules/',
      'build/',
      'dist/',
      '.expo/',
      'coverage/',
      '__mocks__/',
      'temp_*.ts',
      'temp_no_imports.ts',
      'temp_test.ts',
      'app/android/app/build/intermediates/assets/debug/mergeDebugAssets/EXDevMenuApp.android.js', // Specific generated file
      'app/assets/gestureDetector.js', // Another generated file
      'app/index.js', // This file is also generated by the build process
    ],
  }
];