#!/usr/bin/env python3
"""Generate the bundled MLP fallback payload for the React Native app.

This script encodes an `.npz` archive into a TypeScript module so the app can
ship with an offline-ready baseline model without committing binary artifacts.

When a production-quality baseline is available, run the script with
```
python scripts/generate_bundled_mlp_model.py --source path/to/amy_model.npz --version v2025-01-01
```
and commit the updated `app/src/constants/bundledMlpModel.ts` file.

Without a `--source` file the script writes the same zero-initialised baseline
used by `writeMinimalMlpModel` on the server so development builds still have a
consistent shape and label ordering.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import io
import textwrap
from pathlib import Path
from typing import Iterable

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / 'app' / 'src' / 'constants' / 'bundledMlpModel.ts'
DEFAULT_VERSION = 'offline-baseline-v1'
DEFAULT_LABELS = [
    'alle',
    'blau',
    'essen',
    'fertig',
    'gelb',
    'gruen',
    'nochmal',
    'rot',
    'satt',
    'schwester',
    'spielen',
    'trinken',
]
DEFAULT_INPUT_SIZE = 126
DEFAULT_HIDDEN_SIZE = 256


def load_npz_bytes(source: Path | None) -> bytes:
    if source is not None:
        return source.read_bytes()

    labels = np.array(DEFAULT_LABELS, dtype='<U64')
    counts = np.zeros((len(DEFAULT_LABELS),), dtype=np.float32)
    w1 = np.zeros((DEFAULT_HIDDEN_SIZE, DEFAULT_INPUT_SIZE), dtype=np.float32)
    b1 = np.zeros((DEFAULT_HIDDEN_SIZE,), dtype=np.float32)
    w2 = np.zeros((len(DEFAULT_LABELS), DEFAULT_HIDDEN_SIZE), dtype=np.float32)
    b2 = np.zeros((len(DEFAULT_LABELS),), dtype=np.float32)

    buffer = io.BytesIO()
    np.savez(buffer, labels=labels, counts=counts, w1=w1, b1=b1, w2=w2, b2=b2)
    return buffer.getvalue()


def chunk_base64(data: str, width: int = 120) -> Iterable[str]:
    for start in range(0, len(data), width):
        yield data[start : start + width]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, help='Optional .npz file to embed')
    parser.add_argument(
        '--output',
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f'Target TypeScript file (default: {DEFAULT_OUTPUT})',
    )
    parser.add_argument(
        '--version',
        default=DEFAULT_VERSION,
        help=f'Version identifier stored alongside the payload (default: {DEFAULT_VERSION})',
    )
    parser.add_argument(
        '--comment',
        default=None,
        help='Optional extra comment explaining the source of the payload',
    )
    args = parser.parse_args()

    source_bytes = load_npz_bytes(args.source)
    sha256 = hashlib.sha256(source_bytes).hexdigest()
    base64_payload = base64.b64encode(source_bytes).decode('ascii')

    output_lines = [
        '// Auto-generated by scripts/generate_bundled_mlp_model.py.\n',
        '// Do not edit manually.\n',
    ]
    if args.comment:
        for line in textwrap.wrap(args.comment, width=96):
            output_lines.append(f'// {line}\n')
    output_lines.extend(
        [
            'export const BUNDLED_MLP_MODEL_BASE64 =\n',
        ]
    )

    segments = list(chunk_base64(base64_payload, width=120))
    for index, segment in enumerate(segments):
        suffix = " +\n" if index < len(segments) - 1 else '\n'
        output_lines.append(f"  '{segment}'{suffix}")

    output_lines.extend(
        [
            '\n',
            f'export const BUNDLED_MLP_MODEL_BYTES = {len(source_bytes)};\n',
            f"export const BUNDLED_MLP_MODEL_SHA256 = '{sha256}';\n",
            f"export const BUNDLED_MLP_MODEL_VERSION = '{args.version}';\n",
        ]
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(''.join(output_lines))
    print(f'Wrote {args.output} ({len(source_bytes)} bytes, sha256={sha256})')


if __name__ == '__main__':
    main()
